package cn.pickup.launcher;

import org.junit.Test;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * Verifies the pure-Java forward pass against PyTorch outputs.
 * Vectors are generated by ocr-model/gen_test_vectors.py (real pipeline char
 * images + softmax from the trained model).
 */
public class TinyCnnTest {

    private InputStream open(String name) throws Exception {
        File f = new File("src/main/assets/" + name);
        if (f.exists()) {
            return new FileInputStream(f);
        }
        InputStream in = getClass().getClassLoader().getResourceAsStream(name);
        if (in == null) {
            fail("cannot find resource " + name);
        }
        return in;
    }

    @Test
    public void forwardMatchesPyTorch() throws Exception {
        TinyCnn cnn;
        try (InputStream in = open("pickup_ocr.bin")) {
            cnn = TinyCnn.load(in);
        }

        try (DataInputStream dis = new DataInputStream(open("test_vectors.bin"))) {
            int count = dis.readInt();
            assertTrue("empty vectors", count > 0);
            int errors = 0;
            double maxProbError = 0.0;
            for (int s = 0; s < count; s++) {
                float[][] input = new float[28][28];
                for (int y = 0; y < 28; y++) {
                    for (int x = 0; x < 28; x++) {
                        input[y][x] = dis.readFloat();
                    }
                }
                float[] expected = new float[10];
                for (int i = 0; i < 10; i++) {
                    expected[i] = dis.readFloat();
                }
                int argmax = dis.readUnsignedByte();

                TinyCnn.Result r = cnn.predict(input);
                if (r.digit != argmax) {
                    errors++;
                    float[] javaProbs = cnn.distribution(input);
                    StringBuilder sb = new StringBuilder();
                    sb.append("mismatch sample ").append(s).append(" pyArg=").append(argmax)
                            .append(" javaArg=").append(r.digit).append(" javaConf=").append(r.confidence)
                            .append("\n javaProbs=[");
                    for (int i = 0; i < 10; i++) {
                        sb.append(String.format(java.util.Locale.US, "%.6f,", javaProbs[i]));
                    }
                    sb.append("]\n pyProbs=[");
                    for (int i = 0; i < 10; i++) {
                        sb.append(String.format(java.util.Locale.US, "%.6f,", expected[i]));
                    }
                    sb.append("]");
                    System.out.println(sb);
                }
                // recompute probabilities from logits is not exposed; use digit equality
                // plus a soft check: confidence is max prob
                assertTrue("confidence out of range", r.confidence >= 0f && r.confidence <= 1f);
                maxProbError = Math.max(maxProbError, Math.abs(r.confidence - expected[argmax]));
            }
            // allow a tiny float tolerance; argmax must match for all samples
            assertEquals("argmax mismatches", 0, errors);
            assertTrue("max prob error too large: " + maxProbError, maxProbError < 5e-4);
        }
    }
}
